"use client"

import { useEffect } from "react"

export function CodePreview() {
  useEffect(() => {
    // Dynamically import highlight.js to avoid SSR issues
    import("highlight.js").then((hljs) => {
      hljs.default.highlightAll()
    })
  }, [])

  return (
    <section id="playground" className="max-w-7xl mx-auto px-6 pb-32">
      <div className="text-center mb-12 fade" style={{ animationDelay: "240ms" }}>
        <h3 className="text-3xl md:text-4xl font-semibold tracking-tight text-white mb-6">See BLOXSCRIPT in Action</h3>
        <p className="text-lg text-gray-300 max-w-2xl mx-auto">Here's what our AI generates from a simple prompt</p>
      </div>

      <div
        className="fade voxel card3d rounded-xl ring-1 ring-white/10 shadow-2xl overflow-hidden"
        style={{ animationDelay: "360ms" }}
      >
        <div className="bg-[#1e1e2e] px-6 py-4 border-b border-white/10 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <div className="flex gap-2">
              <div className="w-3 h-3 rounded-full bg-[#ff5f56]"></div>
              <div className="w-3 h-3 rounded-full bg-[#ffbd2e]"></div>
              <div className="w-3 h-3 rounded-full bg-[#27ca3f]"></div>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-sm font-medium text-gray-300">weapon-system.lua</span>
              <span className="text-xs px-2 py-1 bg-blue-500/20 text-blue-300 rounded">Lua</span>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <div className="flex items-center gap-2">
              <div className="w-2 h-2 bg-scripton-green rounded-full animate-pulse"></div>
              <span className="text-xs text-scripton-green font-medium">Generated by BLOXSCRIPT AI</span>
            </div>
          </div>
        </div>
        <pre className="overflow-auto p-8 text-sm bg-[#1e1e2e] leading-relaxed">
          <code className="language-lua text-gray-100">
            {`-- Advanced Weapon System Generated by BLOXSCRIPT
-- Place this script in ServerScriptService

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local UserInputService = game:GetService("UserInputService")

-- Create RemoteEvents for client-server communication
local weaponEvents = Instance.new("Folder")
weaponEvents.Name = "WeaponEvents"
weaponEvents.Parent = ReplicatedStorage

local fireEvent = Instance.new("RemoteEvent")
fireEvent.Name = "FireWeapon"
fireEvent.Parent = weaponEvents

-- Weapon Configuration
local WeaponConfig = {
    damage = 25,
    fireRate = 0.1,
    maxAmmo = 30,
    reloadTime = 2.5,
    range = 500
}

-- Handle weapon firing
fireEvent.OnServerEvent:Connect(function(player, targetPosition)
    -- Validate player has weapon equipped
    local character = player.Character
    if not character then return end
    
    -- Create bullet effect and handle damage
    local raycast = workspace:Raycast(character.HumanoidRootPart.Position, 
                                     targetPosition - character.HumanoidRootPart.Position)
    
    if raycast and raycast.Instance.Parent:FindFirstChild("Humanoid") then
        raycast.Instance.Parent.Humanoid:TakeDamage(WeaponConfig.damage)
        print(player.Name .. " hit " .. raycast.Instance.Parent.Name)
    end
end)

print("Weapon system loaded successfully!")`}
          </code>
        </pre>
        <div className="bg-[#1a1a26] px-6 py-4 border-t border-white/10">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className="flex items-center gap-2">
                <span className="text-sm text-scripton-cyan font-medium">Prompt:</span>
                <span className="text-sm text-gray-300">"Create a weapon system with damage and firing mechanics"</span>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-xs text-gray-400">Ready to copy & paste into Roblox Studio</span>
              <button className="px-3 py-1 bg-scripton-cyan/20 hover:bg-scripton-cyan/30 text-scripton-cyan text-xs rounded transition">
                Copy Code
              </button>
            </div>
          </div>
        </div>
      </div>

      <div className="text-center mt-6"></div>
    </section>
  )
}
